document.write('<!-- 用来产生修改状态的ActiveX控件的JS脚本-->   ');
document.write('<!-- 因为微软的ActiveX新机制，需要一个外部引入的js-->   ');
document.write('<object id="TANGER_OCX" classid="clsid:C9BC4DFF-4248-4a3c-8A49-63A7D317F404"    ');
document.write('codebase="/Scripts/officecontrol/OfficeControl.cab#version=5,0,1,6" width="100%" height="100%">   ');
document.write('<param name="IsUseUTF8URL" value="-1">   ');
document.write('<param name="IsUseUTF8Data" value="-1">   ');
document.write('<param name="BorderStyle" value="1">   ');
document.write('<param name="BorderColor" value="14402205">   ');
document.write('<param name="TitlebarColor" value="15658734">   ');
document.write('<param name="TitlebarTextColor" value="0">   ');
document.write('<param name="MenubarColor" value="14402205">   ');
document.write('<param name="MenuButtonColor" VALUE="16180947">   ');
document.write('<param name="MenuBarStyle" value="3">   ');
document.write('<param name="MenuButtonStyle" value="7">   ');
//document.write('<param name="WebUserName" value="NTKO">   ');
document.write('<param name="Caption" value="">   ');
document.write('<param name="MakerCaption" value="北京浩太同益科技发展有限公司">');
document.write('<param name="MakerKey" value="47B5EDE68EE825E3B153E7E3FFB4A23670B942C5">');
document.write('<param name="ProductCaption" value="Processist流程管理系统">');
document.write('<param name="ProductKey" value="292AE94B8D80E53FD80B547181B3DDEE864E294B">');
document.write('<SPAN STYLE="color:red">不能装载文档控件。请在检查浏览器的选项中检查浏览器的安全设置。</SPAN>   ');
document.write('</object>');
